// apps/dashboard/src/modules/Logs.tsx
import { Search, Download, Trash2, Filter, ChevronRight } from 'lucide-react';

const Logs: React.FC = () => {
    const logEntries = [
        { id: '1', level: 'SUCCESS', action: 'Facebook Meta Sync', timestamp: '2026-01-02 17:50:12', message: 'Successfully pulled 15 performance metrics from API.' },
        { id: '2', level: 'INFO', action: 'n8n Workflow Trigger', timestamp: '2026-01-02 17:48:05', message: 'Automation [Daily-IG-Post] initiated by scheduler.' },
        { id: '3', level: 'WARNING', action: 'Notion API Rate Limit', timestamp: '2026-01-02 17:45:30', message: 'Approaching rate limit. Slowing down synchronization throughput.' },
        { id: '4', level: 'SUCCESS', action: 'Gemini Analysis', timestamp: '2026-01-02 17:42:00', message: 'Content sentiment analysis completed for 42 comments.' },
        { id: '5', level: 'ERROR', action: 'Instagram API Auth', timestamp: '2026-01-02 17:35:15', message: 'Access token expired. Re-authentication required.' },
    ];

    return (
        <div className="space-y-8">
            <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
                <div>
                    <h2 className="text-3xl font-bold text-white mb-2">Logs & History</h2>
                    <p className="text-zen-sage text-sm font-medium">Real-time audit trail of all platform operations.</p>
                </div>
                <div className="flex gap-4">
                    <button className="p-3 bg-white/5 border border-white/10 rounded-md text-white/60 hover:text-white transition-all">
                        <Download size={18} />
                    </button>
                    <button className="p-3 bg-red-500/10 border border-red-500/20 rounded-md text-red-400/60 hover:text-red-400 transition-all">
                        <Trash2 size={18} />
                    </button>
                </div>
            </header>

            <div className="glass-dark rounded-lg border border-white/10 overflow-hidden">
                <div className="p-6 border-b border-white/10 flex flex-col md:flex-row gap-4 justify-between bg-black/40">
                    <div className="relative flex-1 max-w-md">
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-white/20" size={16} />
                        <input
                            type="text"
                            placeholder="Search logs by action or message..."
                            className="w-full bg-black/40 border border-white/10 rounded-lg pl-12 pr-4 py-3 text-xs text-white outline-none focus:border-white/40 transition-all"
                        />
                    </div>
                    <div className="flex gap-2">
                        <button className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-md text-[10px] font-bold text-white/40 uppercase tracking-widest hover:bg-white/10 transition-all">
                            <Filter size={14} /> Filter
                        </button>
                        <select className="bg-white/5 border border-white/10 rounded-md px-4 py-2 text-[10px] font-bold text-white/40 uppercase tracking-widest outline-none appearance-none cursor-pointer">
                            <option>All Levels</option>
                            <option>Success</option>
                            <option>Error</option>
                            <option>Warning</option>
                        </select>
                    </div>
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full text-left">
                        <thead>
                            <tr className="border-b border-white/5 text-[10px] font-black text-white/20 uppercase tracking-[0.2em]">
                                <th className="px-8 py-6">Timestamp</th>
                                <th className="px-6 py-6">Level</th>
                                <th className="px-6 py-6">Action</th>
                                <th className="px-6 py-6">Diagnostic Message</th>
                                <th className="px-8 py-6 text-right">Details</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-white/5">
                            {logEntries.map((log) => (
                                <tr key={log.id} className="group hover:bg-white/[0.02] transition-colors">
                                    <td className="px-6 py-6 text-xs text-white/40 font-mono tracking-tighter whitespace-nowrap">
                                        {log.timestamp}
                                    </td>
                                    <td className="px-6 py-6">
                                        <span className={`px-3 py-1 rounded-md text-[9px] font-black tracking-widest uppercase ${log.level === 'SUCCESS' ? 'bg-green-500/10 text-green-400' :
                                            log.level === 'ERROR' ? 'bg-red-500/10 text-red-400' :
                                                log.level === 'WARNING' ? 'bg-orange-500/10 text-orange-400' :
                                                    'bg-blue-500/10 text-blue-400'
                                            }`}>
                                            {log.level}
                                        </span>
                                    </td>
                                    <td className="px-6 py-6 text-sm font-bold text-white tracking-tight">
                                        {log.action}
                                    </td>
                                    <td className="px-6 py-6 text-xs text-white/40 leading-relaxed max-w-xs">
                                        {log.message}
                                    </td>
                                    <td className="px-8 py-6 text-right">
                                        <button className="p-2 rounded-lg bg-white/5 text-white/20 hover:text-white group-hover:translate-x-1 transition-all">
                                            <ChevronRight size={16} />
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                <div className="p-6 border-t border-white/10 flex justify-between items-center text-[10px] font-bold text-white/20 uppercase tracking-widest">
                    <span>Showing 5 of 1,248 entries</span>
                    <div className="flex gap-4">
                        <button className="hover:text-white transition-colors disabled:opacity-30 border-r border-white/10 pr-4" disabled>Previous</button>
                        <button className="hover:text-white transition-colors">Next Page</button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Logs;

// apps/dashboard-nuxt/app/pages/logs.vue
<script setup lang="ts">
import { History, Search, Filter, Download, Terminal, ChevronRight } from 'lucide-vue-next'
import gsap from 'gsap'

const logs = [
  { time: '14:20:01', event: 'AUTH_SUCCESS', agent: 'Aurelius', status: 'OK' },
  { time: '14:22:15', event: 'CONTENT_GEN', agent: 'Zenith', status: 'WARN' },
  { time: '14:25:32', event: 'NOTION_SYNC', agent: 'System', status: 'OK' },
  { time: '14:28:44', event: 'DM_SENT', agent: 'Aurelius', status: 'OK' },
  { time: '14:30:11', event: 'META_WEBHOOK', agent: 'Gateway', status: 'OK' },
]

onMounted(() => {
  gsap.from('.log-row', {
    x: -10,
    opacity: 0,
    duration: 0.5,
    stagger: 0.05,
    ease: 'power2.out'
  })
})
</script>

<template>
  <div class="py-6 space-y-12">
    <header class="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-white/5 pb-10 group">
      <div>
        <h2 class="text-[13px] font-semibold text-perplexity-text-muted">Core auditor trace</h2>
        <h1 class="text-3xl md:text-5xl font-black text-white tracking-tighter leading-none font-sans">Audit Trail</h1>
      </div>
      <div class="flex gap-4">
        <button class="p-3 bg-white/[0.03] border border-white/[0.1] text-white/40 hover:text-white rounded transition-all">
          <Download :size="16" />
        </button>
        <div class="relative group">
          <input 
            type="text" 
            placeholder="FILTER_TRACE..." 
            class="bg-white/[0.03] border border-white/10 rounded-full px-12 py-3 text-[13px] font-medium text-white focus:outline-none focus:border-green-500/30 transition-all w-64"
          >
          <Search :size="14" class="absolute left-6 top-1/2 -translate-y-1/2 text-white/20 group-hover:text-green-500 transition-colors" />
        </div>
      </div>
    </header>

    <div class="stack-trace-box overflow-hidden">
      <div class="stack-trace-header border-b border-white/5">
        <div class="flex items-center gap-12 text-[11px] font-medium text-perplexity-text-muted">
          <span class="w-24">Timestamp</span>
          <span class="w-40">Event identifier</span>
          <span class="w-32">Executor</span>
          <span>Integrity</span>
        </div>
        <button class="flex items-center gap-2 text-[11px] font-semibold text-perplexity-text-muted hover:text-white transition-colors">
          <Filter :size="14" /> Filter trace
        </button>
      </div>

      <div class="divide-y divide-white/[0.03]">
        <div 
          v-for="(log, i) in logs" 
          :key="i" 
          class="log-row p-8 flex items-center justify-between hover:bg-white/[0.02] transition-colors group cursor-pointer"
        >
          <div class="flex items-center gap-4 text-sm font-medium">
            <span class="w-24 text-white/20 font-mono">{{ log.time }}</span>
            <span class="w-40 font-bold tracking-tight">{{ log.event }}</span>
            <span class="w-32 text-indigo-400 font-bold uppercase text-[10px] tracking-widest">{{ log.agent }}</span>
            <span 
              :class="[
                'px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-widest border',
                log.status === 'OK' ? 'bg-green-500/10 border-green-500/20 text-green-400' : 'bg-yellow-500/10 border-yellow-500/20 text-yellow-400'
              ]"
            >
              {{ log.status }}
            </span>
          </div>
          <ChevronRight :size="18" class="text-white/10 group-hover:text-white/40 transition-all group-hover:translate-x-1" />
        </div>
      </div>

      <div class="p-8 bg-white/[0.02] text-center">
        <button class="text-[11px] font-semibold text-perplexity-text-muted hover:text-white transition-colors">
          Load previous operations
        </button>
      </div>
    </div>

    <!-- Live Feed: Technical Module -->
    <div class="stack-trace-box overflow-hidden">
      <div class="stack-trace-header">
        <div class="flex items-center gap-3">
          <Terminal :size="14" class="text-green-500" />
          <span class="text-[13px] font-semibold text-perplexity-text-muted">Institutional stream runtime</span>
        </div>
      </div>
      <div class="p-8 bg-[#0a0a0a] font-mono text-[11px] text-white/30 space-y-2 overflow-y-auto max-h-48">
        <div class="flex gap-4"><span class="text-white/20 select-none">01</span> <span class="text-blue-400/80">[SYSTEM]</span> PUSHING CRYPTOGRAPHICALLY SIGNED EVENT [ID: 0x42A...] TO SECTOR_B</div>
        <div class="flex gap-4"><span class="text-white/20 select-none">02</span> <span class="text-blue-400/80">[GATEWAY]</span> HANDSHAKE SUCCESSFUL WITH META GRAPH API NODE 18.2</div>
        <div class="flex gap-4"><span class="text-white/20 select-none">03</span> <span class="text-blue-400/80">[AGENT]</span> AURELIUS-ALPHA TRANSITIONED TO STATE: MONITORING_NODES</div>
      </div>
    </div>
  </div>
</template>
