// apps/dashboard/src/modules/Settings.tsx
import { Settings as SettingsIcon, Bell, Shield, User, Database, Globe } from 'lucide-react';

const Settings: React.FC = () => {
    return (
        <div className="space-y-8">
            <section className="glass-dark rounded-lg p-8 md:p-12 border border-white/10 relative overflow-hidden">
                <div className="max-w-3xl">
                    <h2 className="text-3xl font-bold text-white mb-4 flex items-center gap-4">
                        <SettingsIcon className="text-white/40" />
                        Platform Settings
                    </h2>
                    <p className="text-zen-sage leading-relaxed mb-10 font-medium">
                        Configure your institutional automation parameters and system preferences.
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <div className="space-y-6">
                            <h3 className="text-[10px] font-bold text-white/40 uppercase tracking-[0.2em] mb-4">Core Configuration</h3>

                            <div className="space-y-4">
                                <label className="block">
                                    <span className="text-xs font-bold text-white/60 uppercase tracking-widest block mb-2">Automation Environment</span>
                                    <select className="w-full bg-black/40 border border-white/10 rounded-lg px-4 py-3 text-sm text-white outline-none focus:border-white/20 appearance-none">
                                        <option value="production">Production Hub</option>
                                        <option value="staging">Staging Node</option>
                                        <option value="development">Local Sandbox</option>
                                    </select>
                                </label>
                                certificates: none
                                <label className="block">
                                    <span className="text-xs font-bold text-white/60 uppercase tracking-widest block mb-2">Primary Sync Target</span>
                                    <div className="relative">
                                        <Database className="absolute left-4 top-1/2 -translate-y-1/2 text-white/20" size={16} />
                                        <input
                                            type="text"
                                            defaultValue="Notion Institutional CRM"
                                            className="w-full bg-black/40 border border-white/10 rounded-lg pl-12 pr-4 py-3 text-sm text-white outline-none focus:border-white/20"
                                        />
                                    </div>
                                </label>
                            </div>
                        </div>

                        <div className="space-y-6">
                            <h3 className="text-[10px] font-bold text-white/40 uppercase tracking-[0.2em] mb-4">System Preferences</h3>

                            <div className="flex items-center justify-between p-4 rounded-lg bg-black border border-white/10">
                                <div className="flex items-center gap-3">
                                    <Bell size={18} className="text-white/40" />
                                    <div>
                                        <p className="text-sm font-bold text-white">Neural Notifications</p>
                                        <p className="text-[10px] text-white/30 uppercase font-bold">Real-time alerts</p>
                                    </div>
                                </div>
                                <div className="w-10 h-6 bg-white rounded-full relative p-1 cursor-pointer">
                                    <div className="absolute right-1 w-4 h-4 bg-black rounded-full shadow-lg" />
                                </div>
                            </div>

                            <div className="flex items-center justify-between p-4 rounded-lg bg-black border border-white/10">
                                <div className="flex items-center gap-3">
                                    <Globe size={18} className="text-white/40" />
                                    <div>
                                        <p className="text-sm font-bold text-white">Global CDN</p>
                                        <p className="text-[10px] text-white/30 uppercase font-bold">Edge delivery</p>
                                    </div>
                                </div>
                                <div className="w-10 h-6 bg-white/10 rounded-full relative p-1 cursor-pointer border border-white/10">
                                    <div className="absolute left-1 w-4 h-4 bg-white/20 rounded-full" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="mt-12 flex gap-4">
                        <button className="px-8 py-4 bg-white text-black rounded-lg font-bold text-xs uppercase tracking-widest hover:bg-zinc-200 transition-all shadow-xl">
                            Deploy Configurations
                        </button>
                        <button className="px-8 py-4 bg-white/5 border border-white/10 text-white rounded-lg font-bold text-xs uppercase tracking-widest hover:bg-white/10 transition-all">
                            Reset to Default
                        </button>
                    </div>
                </div>
            </section>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="glass-dark p-8 rounded-lg border border-white/10 group hover:border-white/20 transition-all">
                    <User className="text-white/20 mb-6 group-hover:scale-110 transition-transform" />
                    <h3 className="text-lg font-bold text-white mb-2">Account Logic</h3>
                    <p className="text-[10px] text-white/40 font-bold uppercase tracking-widest leading-relaxed">
                        Manage institutional credentials and access signatures.
                    </p>
                </div>
                <div className="glass-dark p-8 rounded-lg border border-white/10 group hover:border-white/20 transition-all">
                    <Shield className="text-white/20 mb-6 group-hover:scale-110 transition-transform" />
                    <h3 className="text-lg font-bold text-white mb-2">Security Hash</h3>
                    <p className="text-[10px] text-white/40 font-bold uppercase tracking-widest leading-relaxed">
                        Monitor cryptographic integrity and session tokens.
                    </p>
                </div>
                <div className="glass-dark p-8 rounded-lg border border-white/10 group hover:border-white/20 transition-all">
                    <Database className="text-white/20 mb-6 group-hover:scale-110 transition-transform" />
                    <h3 className="text-lg font-bold text-white mb-2">Data Sovereignty</h3>
                    <p className="text-[10px] text-white/40 font-bold uppercase tracking-widest leading-relaxed">
                        Control local storage and cached intelligence nodes.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default Settings;

// apps/dashboard-nuxt/app/pages/settings.vue
<script setup lang="ts">
import { Settings, Shield, Bell, Database, Globe, Lock, LogOut } from 'lucide-vue-next'
import { signOut } from 'firebase/auth'

const { $auth } = useNuxtApp()
const router = useRouter()

const handleLogout = async () => {
  if (!$auth) return
  await signOut($auth as any)
  router.push('/auth')
}
</script>

<template>
  <div class="py-6 space-y-12">
    <header class="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-white/5 pb-10 group">
      <div>
        <h2 class="text-[13px] font-semibold text-perplexity-text-muted">Core system config</h2>
        <h1 class="text-3xl md:text-5xl font-black text-white tracking-tighter leading-none font-sans">System Settings</h1>
      </div>
      <button 
        @click="handleLogout"
        class="px-8 py-3 bg-red-500/10 border border-red-500/20 text-red-500 rounded-full font-semibold text-[13px] hover:bg-red-500/20 transition-all flex items-center gap-2 active:scale-95"
      >
        <LogOut :size="14" /> TERMINATE_SESSION
      </button>
    </header>

    <div class="grid grid-cols-1 lg:grid-cols-4 gap-12">
      <!-- Sidebar Nav -->
      <nav class="lg:col-span-1 space-y-2">
        <button v-for="item in ['General', 'Security', 'Notifications', 'Integration', 'Advanced']" :key="item" 
          class="w-full text-left px-5 py-3 rounded-xl text-[13px] font-semibold transition-all"
          :class="[item === 'General' ? 'bg-white/10 text-white' : 'text-white/20 hover:text-white/40 hover:bg-white/5']"
        >
          {{ item }}
        </button>
      </nav>

      <!-- Main Settings -->
      <div class="lg:col-span-3 space-y-10">
        <section class="stack-trace-box overflow-hidden">
          <div class="stack-trace-header">
            <h3 class="text-[13px] font-semibold text-perplexity-text-muted">Profile and institutional</h3>
          </div>
          <div class="p-10 bg-[#0a0a0a]">
            <div class="flex flex-col md:flex-row gap-8 items-center">
              <div class="w-14 h-14 rounded bg-white/[0.03] border border-white/[0.08] flex items-center justify-center text-white/20">
                <Settings :size="24" />
              </div>
              <div class="flex-1 space-y-4 w-full">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div class="space-y-2">
                    <label class="text-[11px] font-medium text-perplexity-text-muted ml-1">System handle</label>
                    <input type="text" value="Auto-Notion Institutional" class="w-full bg-[#080808] border border-perplexity-border rounded-xl px-5 py-3 text-[13px] font-medium text-white focus:outline-none focus:border-white/20 transition-all">
                  </div>
                  <div class="space-y-2">
                    <label class="text-[11px] font-medium text-perplexity-text-muted ml-1">Runtime mode</label>
                    <select class="w-full bg-[#080808] border border-perplexity-border rounded-xl px-5 py-3 text-[13px] font-medium text-white focus:outline-none focus:border-white/20 transition-all appearance-none cursor-pointer">
                      <option>HIGH_FIDELITY</option>
                      <option>STANDARD_CORE</option>
                      <option>EFFICIENCY_ENGINE</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section class="stack-trace-box overflow-hidden">
          <div class="stack-trace-header">
            <h3 class="text-[13px] font-semibold text-perplexity-text-muted">Security and protocols</h3>
          </div>
          <div class="p-10 bg-[#0a0a0a] space-y-4">
            <div v-for="s in [
              { label: 'MULTI_FACTOR_AUTH', desc: 'Secure session with MFA encryption layers.', icon: Lock, val: true },
              { label: 'AUTO_LOG_FLUSH', desc: 'Purge operation traces every 24 sectors.', icon: Shield, val: false },
              { label: 'API_GUARD_RUNTIME', desc: 'Rate limit all external graph telemetry.', icon: Globe, val: true }
            ]" :key="s.label" class="flex items-center justify-between p-6 rounded bg-[#080808] border border-white/[0.05] hover:border-green-500/20 transition-colors">
              <div class="flex items-center gap-6">
                <div class="p-3 bg-white/[0.02] text-white/20">
                  <component :is="s.icon" :size="18" />
                </div>
                <div>
                  <h4 class="font-bold text-white/90 text-sm">{{ s.label }}</h4>
                  <p class="text-[11px] text-perplexity-text-muted font-medium mt-1">{{ s.desc }}</p>
                </div>
              </div>
              <div :class="['w-8 h-4 rounded-full relative p-0.5 cursor-pointer transition-all duration-500', s.val ? 'bg-green-500' : 'bg-white/10']">
                <div :class="['w-3 h-3 rounded-full shadow-lg transition-all duration-500', s.val ? 'translate-x-4 bg-black' : 'translate-x-0 bg-white/20']" />
              </div>
            </div>
          </div>
        </section>

        <div class="flex justify-end gap-4">
          <button class="px-8 py-3 bg-white/[0.05] border border-perplexity-border text-white rounded-full font-semibold text-[13px] hover:bg-white/10 transition-all active:scale-95">
            DISCARD
          </button>
          <button class="px-8 py-3 bg-white text-black rounded-full font-semibold text-[13px] hover:bg-white/90 active:scale-95 transition-all shadow-glow-white/10">
            Save system config
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
