// web_app/src/components/Sidebar.tsx
import React, { useState } from 'react';
import {
    LayoutDashboard,
    Share2,
    Database,
    UserPlus,
    Moon,
    Settings,
    CircleCheckBig
} from 'lucide-react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

interface SidebarProps {
    activeTab: string;
    setActiveTab: (tab: string) => void;
}

const Sidebar: React.FC<SidebarProps> = ({ activeTab, setActiveTab }) => {
    const [isOpen, setIsOpen] = useState(false);

    const navItems = [
        { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
        { id: 'ig-connections', label: 'IG Connections', icon: Share2 },
        { id: 'content', label: 'Content Bank', icon: Database },
        { id: 'agents', label: 'AI Agents', icon: UserPlus },
        { id: 'cosmic', label: 'Cosmic Scheduler', icon: Moon },
    ];

    return (
        <>
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="lg:hidden fixed top-6 right-6 z-50 p-3 glass rounded-xl text-white shadow-2xl"
            >
                <LayoutDashboard size={24} />
            </button>

            <aside className={cn(
                "fixed inset-y-0 left-0 z-40 w-72 glass-dark transform transition-transform duration-300 ease-in-out lg:relative lg:translate-x-0 h-full flex flex-col p-6 text-white border-r border-white/5",
                isOpen ? "translate-x-0 shadow-[0_0_50px_rgba(0,0,0,0.8)]" : "-translate-x-full"
            )}>
                <div className="flex items-center gap-3 mb-12 px-2">
                    <div className="w-10 h-10 bg-institutional-indigo rounded-xl flex items-center justify-center shadow-lg shadow-indigo-500/20">
                        <CircleCheckBig size={24} />
                    </div>
                    <div>
                        <h2 className="font-bold text-lg leading-tight">Auto-Notion</h2>
                        <p className="text-[10px] text-white/40 uppercase tracking-widest font-semibold font-sans">Institutional Zen</p>
                    </div>
                </div>

                <nav className="flex-1 space-y-2">
                    {navItems.map((item) => {
                        const Icon = item.icon;
                        const isActive = activeTab === item.id;
                        return (
                            <button
                                key={item.id}
                                onClick={() => {
                                    setActiveTab(item.id);
                                    setIsOpen(false);
                                }}
                                className={cn(
                                    "nav-item w-full group",
                                    isActive ? "nav-item-active" : "nav-item-inactive"
                                )}
                            >
                                <Icon size={20} className={cn(
                                    "transition-transform duration-300",
                                    isActive ? "scale-110" : "group-hover:scale-110"
                                )} />
                                <span className="font-medium text-sm">{item.label}</span>
                            </button>
                        )
                    })}
                </nav>

                <div className="mt-auto space-y-2">
                    <div className="flex gap-2 mb-4 text-[10px] text-white/30 uppercase tracking-widest font-bold px-4">
                        <button onClick={() => { setActiveTab('privacy'); setIsOpen(false); }} className="hover:text-white transition-colors">Privacy</button>
                        <span>•</span>
                        <button onClick={() => { setActiveTab('terms'); setIsOpen(false); }} className="hover:text-white transition-colors">Terms</button>
                        <span>•</span>
                        <button onClick={() => { setActiveTab('deletion'); setIsOpen(false); }} className="hover:text-white transition-colors">Delete</button>
                    </div>
                    <button className="nav-item w-full nav-item-inactive group">
                        <Settings size={20} className="group-hover:rotate-45 transition-transform duration-500" />
                        <span className="font-medium text-sm">Settings</span>
                    </button>

                    <div className="mt-6 p-4 rounded-2xl bg-white/5 border border-white/10">
                        <div className="flex items-center gap-2 mb-2">
                            <span className="text-[10px] font-bold text-zen-sand uppercase tracking-tighter">Mission Status</span>
                            <div className="h-1 flex-1 bg-white/10 rounded-full overflow-hidden">
                                <div className="h-full bg-zen-sand w-[85%] animate-pulse" />
                            </div>
                        </div>
                        <p className="text-[10px] text-white/60 leading-relaxed font-sans">
                            "Integration makes you walk through the door."
                        </p>
                    </div>
                </div>
            </aside>

            {/* Mobile Overlay */}
            {isOpen && (
                <div
                    className="fixed inset-0 bg-black/60 backdrop-blur-sm z-30 lg:hidden"
                    onClick={() => setIsOpen(false)}
                />
            )}
        </>
    );
};

export default Sidebar;

// apps/dashboard-nuxt/app/components/Sidebar.vue
<script setup lang="ts">
import { 
  LayoutDashboard, 
  Share2, 
  UserPlus, 
  Moon, 
  Settings, 
  Zap, 
  History, 
  Link2, 
  BookOpen,
  Activity
} from 'lucide-vue-next'

const props = defineProps<{
  collapsed: boolean
}>()

const emit = defineEmits(['update:collapsed'])

const navItems = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/' },
  { id: 'automation', label: 'Automations', icon: Zap, path: '/automation' },
  { id: 'ig-connections', label: 'Instagram', icon: Share2, path: '/ig-connections' },
  { id: 'content', label: 'Content Library', icon: BookOpen, path: '/content' },
  { id: 'agents', label: 'AI SuperAgents', icon: UserPlus, path: '/super-agents' },
  { id: 'cosmic', label: 'Scheduler', icon: Moon, path: '/cosmic' },
  { id: 'integrations', label: 'Integrations', icon: Link2, path: '/integrations' },
  { id: 'logs', label: 'Logs & History', icon: History, path: '/logs' },
]

const toggleCollapse = () => {
  emit('update:collapsed', !props.collapsed)
}
</script>

<template>
  <aside 
    :class="[
      'hidden lg:flex z-50 bg-perplexity-bg border-r border-perplexity-border h-screen flex-col py-6 px-3 text-white relative shrink-0 transition-all duration-500 ease-in-out',
      collapsed ? 'w-16' : 'w-60'
    ]"
  >
    <!-- Collapse Toggle (Premium) -->
    <button
      @click="toggleCollapse"
      class="absolute -right-3 top-8 p-1.5 rounded-full bg-perplexity-surface border border-perplexity-border text-white/30 hover:text-white transition-all z-50 group hover:scale-110 shadow-xl"
    >
      <Activity 
        :size="11" 
        :class="['transition-transform duration-500', collapsed ? 'rotate-180' : 'rotate-0']" 
      />
    </button>

    <!-- Logo Section (Minimalist) -->
    <div 
      :class="[
        'flex items-center gap-3.5 mb-14 overflow-hidden px-3',
        collapsed ? 'justify-center' : 'justify-start'
      ]"
    >
      <div class="relative flex items-center justify-center shrink-0">
        <div class="absolute inset-0 bg-white/5 blur-lg rounded-full opacity-0 group-hover:opacity-100 transition-opacity" />
        <img src="/logo.svg" alt="Auto-Notion" class="w-7 h-7 object-contain opacity-90 relative z-10" />
      </div>
      <div v-if="!collapsed" class="transition-all duration-500 opacity-100 flex-1">
        <h2 class="font-bold text-lg leading-tight tracking-tight text-white/95">Auto Notion</h2>
      </div>
    </div>

    <!-- Navigation (Pure Icon Style) -->
    <nav class="flex-1 space-y-4">
      <NuxtLink
        v-for="item in navItems"
        :key="item.id"
        :to="item.path"
        :title="collapsed ? item.label : ''"
        class="nav-item group flex items-center gap-4 transition-all duration-300 relative px-4"
        active-class="nav-item-active"
        exact-active-class="nav-item-active"
      >
        <component 
          :is="item.icon" 
          :size="20" 
          class="transition-all duration-300 shrink-0 opacity-40 group-hover:opacity-100 group-hover:scale-110 group-hover:drop-shadow-[0_0_8px_rgba(255,255,255,0.4)]" 
        />
        <span v-if="!collapsed" class="text-[13px] font-medium transition-all duration-300 whitespace-nowrap opacity-60 group-hover:opacity-100">{{ item.label }}</span>
        
        <!-- Hover tooltip for collapsed mode -->
        <div v-if="collapsed" class="absolute left-[calc(100%+1.5rem)] px-4 py-2 bg-perplexity-surface text-white text-[11px] rounded-full font-medium opacity-0 group-hover:opacity-100 transition-all duration-300 whitespace-nowrap pointer-events-none z-50 shadow-2xl border border-perplexity-border translate-x-[-12px] group-hover:translate-x-0">
          {{ item.label }}
        </div>
      </NuxtLink>
    </nav>

    <!-- Footer Section -->
    <div :class="['mt-auto pt-6 transition-all duration-500', collapsed ? 'flex flex-col items-center' : 'px-1']">
      <NuxtLink
        :to="'/settings'"
        :title="collapsed ? 'Settings' : ''"
        class="nav-item group flex items-center gap-4 transition-all duration-300 w-full px-4 active:scale-95"
        active-class="nav-item-active"
      >
        <Settings 
          :size="20" 
          class="shrink-0 opacity-40 group-hover:opacity-100 transition-all duration-500 group-hover:rotate-45 group-hover:drop-shadow-[0_0_8px_rgba(255,255,255,0.3)]" 
        />
        <span v-if="!collapsed" class="text-[13px] font-medium opacity-60 group-hover:opacity-100">Settings</span>
      </NuxtLink>
    </div>
  </aside>
</template>

<style scoped>
.nav-item-active {
  @apply !opacity-100;
}

.nav-item-active :deep(svg) {
  @apply opacity-100 scale-110;
  filter: drop-shadow(0 0 10px rgba(255, 255, 255, 0.5));
}

.nav-item-active span {
  @apply opacity-100;
}
</style>
