// apps/dashboard-nuxt/app/components/Sidebar.vue
<script setup lang="ts">
import { 
  LayoutDashboard, 
  Share2, 
  UserPlus, 
  Moon, 
  Settings, 
  Zap, 
  History, 
  Link2, 
  BookOpen,
  Activity
} from 'lucide-vue-next'

const props = defineProps<{
  collapsed: boolean
}>()

const emit = defineEmits(['update:collapsed'])

const navItems = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/' },
  { id: 'automation', label: 'Automations', icon: Zap, path: '/automation' },
  { id: 'ig-connections', label: 'Instagram', icon: Share2, path: '/ig-connections' },
  { id: 'content', label: 'Content Library', icon: BookOpen, path: '/content' },
  { id: 'agents', label: 'AI SuperAgents', icon: UserPlus, path: '/super-agents' },
  { id: 'cosmic', label: 'Scheduler', icon: Moon, path: '/cosmic' },
  { id: 'integrations', label: 'Integrations', icon: Link2, path: '/integrations' },
  { id: 'logs', label: 'Logs & History', icon: History, path: '/logs' },
]

const toggleCollapse = () => {
  emit('update:collapsed', !props.collapsed)
}
</script>

<template>
  <aside 
    :class="[
      'hidden lg:flex z-50 bg-perplexity-bg border-r border-perplexity-border h-screen flex-col py-6 px-3 text-white relative shrink-0 transition-all duration-500 ease-in-out',
      collapsed ? 'w-16' : 'w-60'
    ]"
  >
    <!-- Collapse Toggle (Premium) -->
    <button
      @click="toggleCollapse"
      class="absolute -right-3 top-8 p-1.5 rounded-full bg-perplexity-surface border border-perplexity-border text-white/30 hover:text-white transition-all z-50 group hover:scale-110 shadow-xl"
    >
      <Activity 
        :size="11" 
        :class="['transition-transform duration-500', collapsed ? 'rotate-180' : 'rotate-0']" 
      />
    </button>

    <!-- Logo Section (Minimalist) -->
    <div 
      :class="[
        'flex items-center gap-3.5 mb-14 overflow-hidden px-3',
        collapsed ? 'justify-center' : 'justify-start'
      ]"
    >
      <div class="relative flex items-center justify-center shrink-0">
        <div class="absolute inset-0 bg-white/5 blur-lg rounded-full opacity-0 group-hover:opacity-100 transition-opacity" />
        <img src="/logo.svg" alt="Auto-Notion" class="w-7 h-7 object-contain opacity-90 relative z-10" />
      </div>
      <div v-if="!collapsed" class="transition-all duration-500 opacity-100 flex-1">
        <h2 class="font-bold text-lg leading-tight tracking-tight text-white/95">Auto Notion</h2>
      </div>
    </div>

    <!-- Navigation (Pure Icon Style) -->
    <nav class="flex-1 space-y-4">
      <NuxtLink
        v-for="item in navItems"
        :key="item.id"
        :to="item.path"
        :title="collapsed ? item.label : ''"
        class="nav-item group flex items-center gap-4 transition-all duration-300 relative px-4"
        active-class="nav-item-active"
        exact-active-class="nav-item-active"
      >
        <component 
          :is="item.icon" 
          :size="20" 
          class="transition-all duration-300 shrink-0 opacity-40 group-hover:opacity-100 group-hover:scale-110 group-hover:drop-shadow-[0_0_8px_rgba(255,255,255,0.4)]" 
        />
        <span v-if="!collapsed" class="text-[13px] font-medium transition-all duration-300 whitespace-nowrap opacity-60 group-hover:opacity-100">{{ item.label }}</span>
        
        <!-- Hover tooltip for collapsed mode -->
        <div v-if="collapsed" class="absolute left-[calc(100%+1.5rem)] px-4 py-2 bg-perplexity-surface text-white text-[11px] rounded-full font-medium opacity-0 group-hover:opacity-100 transition-all duration-300 whitespace-nowrap pointer-events-none z-50 shadow-2xl border border-perplexity-border translate-x-[-12px] group-hover:translate-x-0">
          {{ item.label }}
        </div>
      </NuxtLink>
    </nav>

    <!-- Footer Section -->
    <div :class="['mt-auto pt-6 transition-all duration-500', collapsed ? 'flex flex-col items-center' : 'px-1']">
      <NuxtLink
        :to="'/settings'"
        :title="collapsed ? 'Settings' : ''"
        class="nav-item group flex items-center gap-4 transition-all duration-300 w-full px-4 active:scale-95"
        active-class="nav-item-active"
      >
        <Settings 
          :size="20" 
          class="shrink-0 opacity-40 group-hover:opacity-100 transition-all duration-500 group-hover:rotate-45 group-hover:drop-shadow-[0_0_8px_rgba(255,255,255,0.3)]" 
        />
        <span v-if="!collapsed" class="text-[13px] font-medium opacity-60 group-hover:opacity-100">Settings</span>
      </NuxtLink>
    </div>
  </aside>
</template>

<style scoped>
.nav-item-active {
  @apply !opacity-100;
}

.nav-item-active :deep(svg) {
  @apply opacity-100 scale-110;
  filter: drop-shadow(0 0 10px rgba(255, 255, 255, 0.5));
}

.nav-item-active span {
  @apply opacity-100;
}
</style>

// apps/dashboard/src/components/Sidebar.tsx
import React, { useState } from 'react';
import {
    LayoutDashboard,
    Share2,
    UserPlus,
    Moon,
    Settings,
    Zap,
    History,
    Link2,
    BookOpen,
    Activity
} from 'lucide-react';
import { motion } from 'framer-motion';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { NavLink } from 'react-router-dom';

function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

interface SidebarProps {
    collapsed: boolean;
    setCollapsed: (collapsed: boolean) => void;
}

const Sidebar: React.FC<SidebarProps> = ({
    collapsed,
    setCollapsed
}) => {
    const [isOpen, setIsOpen] = useState(false);

    const navItems = [
        { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/dashboard' },
        { id: 'automation', label: 'Automations', icon: Zap, path: '/automation' },
        { id: 'ig-connections', label: 'Instagram', icon: Share2, path: '/ig-connections' },
        { id: 'content', label: 'Content Library', icon: BookOpen, path: '/content' },
        { id: 'agents', label: 'SUPER AGENTS ADVANCED', icon: UserPlus, path: '/super-agents' },
        { id: 'cosmic', label: 'Scheduler', icon: Moon, path: '/cosmic' },
        { id: 'integrations', label: 'Integrations', icon: Link2, path: '/integrations' },
        { id: 'logs', label: 'Logs & History', icon: History, path: '/logs' },
    ];

    return (
        <>
            <motion.aside
                initial={false}
                animate={{
                    width: collapsed ? 100 : 320,
                    x: 0
                }}
                className={cn(
                    "hidden lg:flex fixed inset-y-0 left-0 z-40 glass-dark h-full flex-col p-8 text-white border-r-0.5 border-white/5 relative shrink-0 overflow-hidden",
                    isOpen ? "!flex translate-x-0 shadow-[0_0_100px_rgba(0,0,0,0.9)]" : "lg:flex"
                )}
            >
                {/* Collapse Toggle */}
                <button
                    onClick={() => setCollapsed(!collapsed)}
                    className="absolute right-4 top-8 p-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-white/40 hover:text-white transition-all z-50"
                >
                    <Activity size={16} className={cn("transition-transform duration-500", collapsed ? "rotate-180" : "rotate-0")} />
                </button>

                <div className={cn("flex items-center gap-4 mb-16 px-2 overflow-hidden whitespace-nowrap", collapsed && "justify-center px-0")}>
                    <div className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0 overflow-hidden">
                        <img src="/logo.svg" alt="Auto-Notion" className="w-full h-full object-contain" />
                    </div>
                    {!collapsed && (
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                            <h2 className="font-bold text-xl leading-tight tracking-tight">Auto-Notion</h2>
                            <p className="text-[10px] text-white/40 uppercase tracking-[0.2em] font-bold font-sans">Institutional Zen</p>
                        </motion.div>
                    )}
                </div>

                <nav className="flex-1 space-y-3">
                    {navItems.map((item) => {
                        const Icon = item.icon;
                        return (
                            <NavLink
                                key={item.id}
                                to={item.path}
                                end={item.path === '/dashboard'}
                                onClick={() => setIsOpen(false)}
                                title={collapsed ? item.label : ""}
                                className={({ isActive }) => cn(
                                    "nav-item w-full group py-4 transition-all duration-500 flex items-center gap-3 px-4 rounded-lg",
                                    collapsed ? "justify-center" : "justify-start",
                                    isActive ? "nav-item-active bg-white/10 text-white shadow-[inset_0_0_20px_rgba(255,255,255,0.05)]" : "nav-item-inactive text-white/40 hover:bg-white/5"
                                )}
                            >
                                <Icon size={18} className="transition-all duration-500 group-hover:scale-110 shrink-0" />
                                {!collapsed && <span className="font-bold text-sm tracking-wide">{item.label}</span>}
                            </NavLink>
                        )
                    })}
                </nav>

                <div className={cn("mt-auto pb-6", collapsed && "flex flex-col items-center")}>
                    {!collapsed && (
                        <div className="flex gap-4 mb-6 text-[9px] text-white/30 uppercase tracking-[0.15em] font-extrabold px-4">
                            <NavLink to="/privacy" className="hover:text-white transition-colors">Privacy</NavLink>
                            <span>•</span>
                            <NavLink to="/terms" className="hover:text-white transition-colors">Terms</NavLink>
                        </div>
                    )}

                    <NavLink
                        to="/settings"
                        title={collapsed ? "Settings" : ""}
                        className={({ isActive }) => cn(
                            "nav-item w-full group py-4 border-t-0.5 border-white/5 rounded-none mt-4 flex items-center gap-3 px-4",
                            collapsed ? "justify-center" : "justify-start",
                            isActive ? "text-white" : "text-white/40"
                        )}
                    >
                        <Settings size={18} className="group-hover:rotate-90 transition-transform duration-700 shrink-0" />
                        {!collapsed && <span className="font-bold text-sm tracking-wide">Settings</span>}
                    </NavLink>
                </div>
            </motion.aside>

            {/* Mobile Overlay */}
            {isOpen && (
                <div
                    className="fixed inset-0 bg-black/80 backdrop-blur-md z-30 lg:hidden transition-opacity duration-500"
                    onClick={() => setIsOpen(false)}
                />
            )}
        </>
    );
};

export default Sidebar;
